---


S1:
    hostname: 192.168.31.101
    groups:
        - cisco_group
    data:
        all: yes
        routing: yes


S2:
    hostname: 192.168.31.102
    groups:
        - cisco_group
    data:
        all: yes
        routing: yes



S3:
    hostname: 192.168.31.103
    groups:
        - cisco_group
    data:
        all: yes
        routing: yes
        etherchannel: yes
        trunking: yes
        vlan: yes


S4:
    hostname: 192.168.31.104
    groups:
        - cisco_group
    data:
        all: yes
        routing: yes
        etherchannel: yes
        trunking: yes
        vlan: yes



S5:
    hostname: 192.168.31.105
    groups:
        - cisco_group
    data:
        all: yes
        trunking: yes
        vlan: yes


S6:
    hostname: 192.168.31.106
    groups:
        - cisco_group
    data:
        all: yes
        trunking: yes
        vlan: yes


S7:
    hostname: 192.168.31.107
    groups:
        - cisco_group
    data:
        all: yes
        trunking: yes
        vlan: yes
